name: veriface-id
options:
  bundleIdPrefix: com.verifaceid
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  groupSortPosition: top

targets:
  veriface-id:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: veriface-id
        type: group
    settings:
      INFOPLIST_FILE: veriface-id/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.verifaceid.app
      PRODUCT_NAME: veriface-id
      INFOPLIST_KEY_NSCameraUsageDescription: "This app needs camera access to capture high-quality photos of driver's license documents for validation."
      INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "This app needs access to your photo library to select existing driver's license images for validation."
      INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchScreen_Generation: YES
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
    info:
      path: veriface-id/Info.plist
      properties:
        CFBundleDisplayName: "Veriface ID"
        CFBundleName: "veriface-id"
        CFBundleIdentifier: com.verifaceid.app
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0"
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "This app needs camera access to capture high-quality photos of driver's license documents for validation."
        NSPhotoLibraryUsageDescription: "This app needs access to your photo library to select existing driver's license images for validation."
